import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const dir=path.dirname(fileURLToPath(import.meta.url));
const root=path.dirname(dir);
const dataUri=(file)=>`data:image/${path.extname(file)==='.webp'?'webp':'png'};base64,${fs.readFileSync(file).toString('base64')}`;
const image=(name)=>dataUri(path.join(dir,'assets',name+'.webp'));
const logo=(name,label)=>`<img class="ys-logo" src="${dataUri(path.join(root,'public/logos',name+'.png'))}" alt="${label} logo">`;
const illustration=(name,cls='')=>`<figure class="ys-illustration ${cls}"><img src="${image(name)}" alt="Hand-drawn Japanese dream garden illustration"><figcaption>Concept artwork · GPT Image 2.5 Sunburst on fal · not gameplay</figcaption></figure>`;
const slides=[
 {tag:'01 / THE IDEA',title:'What if your words<br>could change a world?',sub:'Yume 夢 · a living Japanese-learning game',time:'00:00–00:25',body:`<div class="ys-hero-copy"><p class="ys-hand ys-motto">Speak Japanese.<br>Watch meaning become visible.</p><p class="ys-small">Built by Ronit for the Visko Orbis Challenge</p><div class="ys-brand-row">${logo('visko','Visko')}${logo('reactor','Reactor')}<span>Live world powered by Orbis</span></div></div>${illustration('dream-world','ys-hero-art')}`,say:'What if your words could change a world? I’m Ronit, and this is Yume, a Japanese-learning game built around a simple idea: when your meaning is understood, the world responds. Yume means dream. I wanted to turn language practice into a place you can shape, not just a question you can answer.',cue:'Start looking at the camera. This is concept artwork, not a product screenshot. Transition to the motivation, then the real demo on slide 3.'},
 {tag:'02 / WHY I BUILT IT',title:'Less guessing.<br>More expressing.',sub:'I wanted Japanese practice where your words actually do something.',time:'00:25–00:50',body:`${illustration('words-become-world','ys-why-art')}<div class="ys-comparison"><div><span class="ys-label">RECOGNITION</span><p class="ys-hand">“Which answer is right?”</p></div><span class="ys-arrow">→</span><div><span class="ys-label">EXPRESSION</span><p class="ys-hand">“How do I make it happen?”</p></div></div>`,say:'Recognizing an answer and expressing an idea are different experiences. I wanted practice where Japanese does something, rather than only earning a check mark. Yume takes inspiration from kotodama, the idea that words can shape reality. The product turns that metaphor into a small, repeatable interaction.',cue:'This is a product-design motivation, not a fabricated personal learning history. Tell a true personal example instead if you have one.'},
 {tag:'03 / WHAT I BUILT + DEMO',title:'Your Japanese is<br>the next move.',sub:'An objective. Your words. Feedback. A change in the running world.',time:'00:50–01:45',body:`<div class="ys-demo-layout"><div class="ys-demo-board"><span class="ys-label">PARK OBJECTIVE</span><h3>Put a cat in the park.</h3><p class="ys-jp">こうえんに ねこが います。</p><p>There is a cat in the park.</p><div class="ys-demo-path"><span>Meaning understood</span><b>→</b><span>Steer Orbis</span></div><div class="ys-record-note">Recording slot: replace with your real app demo later.</div></div><div class="ys-demo-side"><h3 class="ys-hand">Then try again.</h3><p>Wrong meaning → feedback only</p><p>Correct meaning → next scene change</p><hr><p><b>3 guided worlds</b><br>Park · Classroom · Night City</p><p><b>4 difficulty levels</b><br>Single word → description</p><p><b>Learning support</b><br>Spoken narration · saved vocabulary</p></div></div>`,say:'Here is the loop. The objective asks for a cat in the park. I type, “こうえんに ねこが います.” It means, “There is a cat in the park.” Yume checks the meaning and sends the accepted scene change to Orbis. Now I try an unrelated answer at the next objective. I get feedback, without a new steering command. Then I correct it: “いぬが ねこの となりに います.” A dog is next to the cat. The next change goes into the same running session. The prototype also includes three guided worlds, four difficulty levels, narration, and vocabulary saving.',cue:'RECORD LATER. Allow 15–20 seconds within this section for real responses. Show one uninterrupted correct turn, an incorrect English answer such as “I like pizza,” then the corrected dog turn. Use sentence-level difficulty. Only describe results visible in the recording. Do not claim rejection freezes the existing video. Mic input is optional, text is the reliable recording path.'},
 {tag:'04 / HOW IT WORKS',title:'Language becomes<br>a control signal.',sub:'A focused stack. One clear role for each layer.',time:'01:45–02:30',body:`<div class="ys-flow"><div><span class="ys-label">INPUT</span><b>Japanese</b><small>Text / Web Speech API</small></div><span>→</span><div><span class="ys-label">INTERPRET</span><b>Next.js → Groq</b><small>Check meaning + correction</small></div><span>→</span><div><span class="ys-label">STEER</span><b>Reactor → Orbis</b><small>Running prompt / set_prompt</small></div></div><div class="ys-stack-grid"><div>${logo('nextjs','Next.js')}<b>Application</b><p>Next.js 16 · React 19<br>TypeScript · API routes · CSS</p></div><div>${logo('groq','Groq')}<b>Language inference</b><p>Meaning grading<br>Scene-text narration</p></div><div>${logo('visko','Visko')}${logo('reactor','Reactor')}<b>Live video</b><p>Visko Orbis · Reactor SDK<br>WebRTC · prompt steering</p></div><div>${logo('fish-audio','Fish Audio')}<b>Voice</b><p>Fish Audio TTS<br>Browser speech recognition</p></div><div><span class="ys-local-mark">{ }</span><b>Local state</b><p>React state · localStorage<br>Saved words, no account needed</p></div><div>${logo('fal','fal')}<b>Supporting visuals</b><p>fal.ai artwork tooling<br>Sunburst presentation images</p></div></div>`,say:'The app uses Next.js, React, and TypeScript. A server route sends the learner’s answer to Groq for language-model inference. In guided mode, an accepted answer unlocks a predefined scene addition. The app updates the running scene prompt, and the Reactor SDK sends set_prompt to steer Visko Orbis over the live connection. Fish Audio provides Japanese speech, browser speech recognition supports microphone input, and local storage keeps saved vocabulary. fal provides supporting artwork, including these presentation illustrations. It is not the live-video engine.',cue:'User-confirmed provider: Groq. Verify the final deployed Groq model before publishing. Do not invent a model name or measured speedup. Narration uses scene text, not visual frame analysis. Fixed-scenario keyword fallback does not make the whole app offline. Brand logos are local project assets, not generated imitations.'},
 {tag:'05 / WHY ORBIS MATTERS',title:'The video is not decoration.<br>It is the response.',sub:'The learner’s next answer influences a world that is already running.',time:'02:30–02:55',body:`<div class="ys-proof-row"><div><span class="ys-label">NOT THE EXPERIENCE</span><p class="ys-hand">Pick an answer.<br>Play a fixed clip.</p><small>A predetermined visual result.</small></div><span class="ys-arrow">→</span><div><span class="ys-label">THE YUME LOOP</span><p class="ys-hand">Express a change.<br>Steer the live world.</p><small>New input, interpreted turn after turn.</small></div></div><div class="ys-thesis"><span>Japanese input</span><b>→</b><span>Meaning check</span><b>→</b><span>Live consequence</span></div><p class="ys-bottom-note">Real-time steering is part of the learning mechanic, not an extra effect.</p>`,say:'Orbis matters because the learner keeps interacting with an already-running world. A fixed clip cannot respond to a new answer. Yume uses live steering as part of the learning mechanic: input, interpretation, consequence, and another attempt. That is the distinction I want this prototype to demonstrate, rather than just showing an attractive generated video.',cue:'Show actual consecutive turns if footage is available. Do not promise perfect persistence, instant response, or objectively improved learning without evidence.'},
 {tag:'06 / YUME 夢',title:'Don’t just learn the word.<br>Give it a world.',sub:'Speak Japanese. Watch your words become reality.',time:'02:55–03:15',body:`<div class="ys-closing-copy"><p class="ys-hand">A dream you shape,<br>one sentence at a time.</p><div class="ys-next"><span class="ys-label">NEXT TO PROVE</span><p>Reliable live turns<br>Learner testing<br>Richer expression</p></div><p class="ys-small">Ronit · Visko Orbis Challenge</p></div>${illustration('dream-world','ys-close-art')}`,say:'The next step is to validate the live loop reliably and test the experience with learners. I want to understand whether people can express the intended meaning, recover from mistakes, and want to try another turn. That is Yume: a dream you shape, one sentence at a time. Thank you.',cue:'Look back at the camera. Add verified public app and repository links in your final edit. Update future work after testing, but do not invent completed validation or user results.'}
];
const css=fs.readFileSync(path.join(dir,'whiteboard.css'),'utf8');
const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Yume · Six-slide presentation</title><style>${css}</style></head><body><main id="viewport"><div id="deck">${slides.map((s,i)=>`<section class="ys-slide${i===0?' is-active':''}" data-slide="${i+1}" aria-label="Slide ${i+1}: ${s.tag}" aria-hidden="${i!==0}"><header><span class="ys-eyebrow">${s.tag}</span><h1>${s.title}</h1><p class="ys-subtitle">${s.sub}</p></header><div class="ys-content">${s.body}</div><footer><span>YUME · VISKO ORBIS CHALLENGE</span><span>${String(i+1).padStart(2,'0')} / 06</span></footer><div class="ys-camera-guide">your camera</div></section>`).join('')}</div></main><aside id="notes" hidden></aside><nav id="controls" aria-label="Presentation controls"><button id="prev" aria-label="Previous slide">←</button><span id="counter" aria-live="polite"></span><button id="next" aria-label="Next slide">→</button><button id="noteBtn">Notes · N</button><button id="full">Fullscreen · F</button><button id="clean">Clean view · H</button><button id="print">Print / PDF</button></nav><script>
const data=${JSON.stringify(slides.map(({tag,time,say,cue})=>({tag,time,say,cue}))).replaceAll('<','\\u003c')};
const slides=[...document.querySelectorAll('.ys-slide')];let index=0;
const notes=document.getElementById('notes');
function resize(){const controls=document.body.classList.contains('clean')?0:72;const scale=Math.min(innerWidth/1600,Math.max(1,innerHeight-controls)/900);const deck=document.getElementById('deck');deck.style.transform='scale('+scale+')';document.getElementById('viewport').style.height=(innerHeight-controls)+'px';}
function show(n){index=Math.max(0,Math.min(slides.length-1,n));slides.forEach((s,i)=>{s.classList.toggle('is-active',i===index);s.setAttribute('aria-hidden',String(i!==index))});document.getElementById('counter').textContent=(index+1)+' / '+slides.length;notes.replaceChildren();for(const text of [data[index].time,data[index].say,'Recording direction: '+data[index].cue]){const p=document.createElement('p');p.textContent=text;notes.append(p)}history.replaceState(null,'','#'+(index+1));}
function toggleNotes(){notes.hidden=!notes.hidden;}
function clean(){document.body.classList.toggle('clean');notes.hidden=true;resize();}
async function full(){try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch{}}
document.getElementById('prev').onclick=()=>show(index-1);document.getElementById('next').onclick=()=>show(index+1);document.getElementById('noteBtn').onclick=toggleNotes;document.getElementById('clean').onclick=clean;document.getElementById('full').onclick=full;document.getElementById('print').onclick=()=>print();
addEventListener('resize',resize);addEventListener('keydown',e=>{if(['ArrowRight','ArrowDown',' ','PageDown'].includes(e.key)){e.preventDefault();show(index+1)}if(['ArrowLeft','ArrowUp','PageUp'].includes(e.key)){e.preventDefault();show(index-1)}if(e.key==='Home')show(0);if(e.key==='End')show(slides.length-1);if(e.key.toLowerCase()==='n')toggleNotes();if(e.key.toLowerCase()==='h')clean();if(e.key.toLowerCase()==='f')full();if(e.key==='Escape'){document.body.classList.remove('clean');notes.hidden=true;resize()}});show((Number(location.hash.slice(1))||1)-1);resize();
</script></body></html>`;
fs.writeFileSync(path.join(dir,'yume-slides.html'),html);
fs.writeFileSync(path.join(dir,'slides.json'),JSON.stringify(slides.map(({body,...s})=>s),null,2));
fs.writeFileSync(path.join(dir,'SCRIPT.md'),'# Yume · Six-slide recording script\n\nTarget: approximately 3 minutes 15 seconds, including real demo pauses. Confirm the challenge duration before submission. Visual style is inspired by sampled frames from the supplied reference. Groq is the user-confirmed provider. Demo recording is deferred until the app is ready.\n\n'+slides.map((s,i)=>`## ${i+1}. ${s.title.replaceAll('<br>',' ')}\n\n**Time: ${s.time}**\n\n${s.say}\n\n**Recording direction:** ${s.cue}\n`).join('\n'));
console.log('Built 6 slides, 2 embedded Sunburst artworks, 6 stack brand logos, and matching narration.');
