import fs from 'node:fs';
import vm from 'node:vm';
const html=fs.readFileSync(new URL('./yume-slides.html',import.meta.url),'utf8');
const classes=[...html.matchAll(/<section class="([^"]+)"/g)].map(m=>m[1].split(' '));
if(classes.length!==6)throw Error('Expected exactly six slides');
if(classes.some(c=>c.some(n=>!['ys-slide','is-active'].includes(n))))throw Error('Unexpected layout class on slide');
if(classes.filter(c=>c.includes('is-active')).length!==1)throw Error('Expected one active slide');
const images=[...html.matchAll(/<img[^>]+src="([^"]+)"/g)];
if(images.length!==11||images.some(m=>!m[1].startsWith('data:image/')))throw Error('Image embedding regression');
if(!html.includes('Groq')||html.includes('OpenRouter'))throw Error('Stack content regression');
if(/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}:[0-9a-f]{32}/i.test(html))throw Error('Potential credential found');
new vm.Script(html.match(/<script>([\s\S]*?)<\/script>/)[1]);
const script=fs.readFileSync(new URL('./SCRIPT.md',import.meta.url),'utf8');
if([...script.matchAll(/^## /gm)].length!==6)throw Error('Script and slides out of sync');
console.log('PASS: six slides, one visible by default, 11 embedded images/logos, six narration sections, Groq stack, valid JS, no fal credential pattern.');
